import CardInterface from "../interface/cardInterface"

export const CARD: CardInterface[] = [
    {
        id:1,
        bannerId:1,
        page:['remote-assistant'],
        image:'./img/question.png',
        title:'Creación de asistencia',
        text:'Inicie una solicitud de asistencia en tiempo real o programada.',       
    },
    {
        id:2,
        bannerId:1,
        page:[ 'remote-assistant'],        
        image:'./img/glasses.png',
        title:'Comunicación con realidad mixta',
        text:'Realice videollamadas para mostrar el entorno, describir el problema y resolver dudas.',       
    },
    {
        id:3,
        bannerId:1,
        page:[ 'remote-assistant'],        
        image:'./img/bubble.png',
        title:'Captura de pantalla y anotaciones',
        text:'Capture imágenes y realice anotaciones visuales para una mejor orientación.',       
    },
    {
        id:4,
        bannerId:1,
        page:[ 'remote-assistant'],        
        image:'./img/chat.png',
        title:'Interacción en tiempo real',
        text:'Colaboración entre expertos con mensajes, archivos y chats interactivos.',       
    },
    {
        id:5,
        bannerId:1,
        page:[ 'remote-assistant'],        
        image:'./img/person.png',
        title:'Registro de la Sesión',
        text:'Historial de la sesión para futuras referencias y mejoras.',       
    },
    {
        id:6,
        bannerId:1,
        page:[ 'remote-assistant'],        
        image:'./img/refresh.png',
        title:'Mejoras Continuas',
        text:'Implementación de mejoras basadas en comentarios y experiencia de usuario para una asistencia más eficiente.',       
    },
    {
        id:7,
        bannerId:5,
        page:[ 'remote-assistant'],
        number:"1",                
        heading:'Soluciones ágiles',
        text:'Evita largos períodos de inactividad al resolver problemas técnicos en tiempo real.',       
        description:'Al permitir una comunicación en tiempo real entre expertos y operarios, y una mejor visualización gracias al soporte de las gafas de realidad mixta, agiliza la resolución de problemas dentro de la planta, evita largos períodos de inactividad y mejora la eficiencia operativa.'
    },
    {
        id:8,
        bannerId:5,
        page:[ 'remote-assistant'],                
        number:"2",                        
        heading:'Distancias',
        text:'Supera barreras geográficas para acceder a expertos altamente especializados globalmente.',       
        description:'Conecta a expertos altamente especializados de cualquier ubicación con los operarios que necesiten asistencia. ¡No hay limitaciones geográficas!'
    },
    {
        id:9,
        bannerId:5,
        page:[ 'remote-assistant'],
        number:"3",                
        heading:'Seguridad en la planta',
        text:'Servicio de capacitación personalizada y consultoría inicial.',       
        description:'Remote Assistance brinda un servicio integral que incluye capacitación y consultoría inicial. Esto contribuye a mejorar la seguridad en la planta, con una formación adaptada a los procesos de la empresa. La consultoría inicial ayuda a implementar prácticas de seguridad y eficiencia, asegurando un uso óptimo del sistema.'
    },
    {
        id:10,
        bannerId:5,
        page:[ 'remote-assistant'],                
        number:"4",                        
        heading:'Adaptabilidad y personalización',
        text:'Ofrece soluciones ajustadas a las necesidades específicas de cada empresa para una mejor adaptación.',       
        description:'Se ajusta y personaliza para cumplir con las necesidades específicas de cada industria. Esto implica proporcionar soluciones y recomendaciones a medida que se adapten perfectamente a los procesos y sistemas particulares de los clientes.'
    },
    {
        id:11,
        bannerId:6,
        page:['remote-assistant'],
        image:'./img/chart.png',
        title:'Reduce costos',
        text:'Elimina gastos de viajes y viáticos al ofrecer asistencia remota.',       
    },
    {
        id:12,
        bannerId:6,
        page:[ 'remote-assistant'],        
        image:'./img/refresh.png',
        title:'Colaboración a distancia',
        text:'Mejora la comunicación visual y práctica entre equipos que se encuentran en diferentes lugares.',       
    },
    {
        id:13,
        bannerId:6,
        page:[ 'remote-assistant'],        
        image:'./img/lock.png',
        title:'Formación y capacitación',
        text:'Realice videollamadas para mostrar el entorno, describir el problema y resolver dudas.',       
    },
    {
        id:14,
        bannerId:6,
        page:[ 'remote-assistant'],        
        image:'./img/chat.png',
        title:'Experiencia del cliente',
        text:'Respuestas rápidas y asistencia inmediata para una mejor experiencia del cliente.',       
    },
    {
        id:15,
        bannerId:7,
        page:['remote-assistant'],
        number:"1",                
        heading:'Análisis y propuesta personalizada',
        text:'Evaluación de necesidades seguida de una propuesta adaptada con detalles como licencias, soporte, costos.',
    },
    {
        id:16,
        bannerId:7,
        page:['remote-assistant'],
        number:"2",                
        heading:'Configuración y formación',
        text:'Configuración del sistema y capacitación del personal para un uso efectivo.',
    },
    {
        id:17,
        bannerId:7,
        page:['remote-assistant'],
        number:"3",                
        heading:'Consultoría y adaptación a Procesos',
        text:'Asesoramiento para integrar la asistencia remota y adaptarla a los procesos existentes.',
    },
    {
        id:18,
        bannerId:7,
        page:['remote-assistant'],
        number:"4",                
        heading:'Intalación física o virtual',
        text:'Implementación y configuración de dispositivos tecnológicos específicos',
    },
    {
        id:19,
        bannerId:7,
        page:['remote-assistant'],
        number:"5",                
        heading:'Operación regular y soporte inicial',
        text:'Uso regular del servicio con soporte técnico inicial para una implementación sin problemas.',
    },
    {
        id:20,
        bannerId:7,
        page:['remote-assistant'],
        number:"6",                
        heading:'Evaluación Continua y Mejora',
        text:'Evaluaciones constantes con actualizaciones y mejoras según las necesidades identificadas.',
    },

    {
        id:21,
        bannerId:1,
        page:['smart-rutines'],
        image:'./img/multi.png',
        title:'Multiplataforma',
        text:'Define rutinas según roles y necesidades, crea pasos esenciales para cada tarea y accede desde múltiples plataformas para una adaptabilidad total.',       
    },
    {
        id:22,
        bannerId:1,
        page:[ 'smart-rutines'],        
        image:'./img/refresh.png',
        title:'Registro integral de datos',
        text:'Almacena información detallada tanto en modo offline como online, asegurando un seguimiento completo y preciso de todas las actividades realizadas.',       
    },
    {
        id:23,
        bannerId:1,
        page:[ 'smart-rutines'],        
        image:'./img/glasses.png',
        title:'Manos libres',
        text:'Los operarios pueden completar sus rutinas de manera efectiva. Usá realidad aumentada para obtener información de valor en tiempo real para completar las rutinas.',       
    },
    {
        id:24,
        bannerId:5,
        page:[ 'smart-rutines'],
        number:"1",                
        heading:'Verificación de componentes',
        text:'Reemplaza verificaciones manuales por rutinas de seguridad inteligentes.',       
        description:'Reemplaza procesos manuales de verificación por rutinas de seguridad inteligentes, mejorando la precisión en la evaluación de componentes críticos. Esto garantiza un control más exhaustivo y confiable de los elementos clave en la industria.'
    },
    {
        id:25,
        bannerId:5,
        page:[ 'smart-rutines'],                
        number:"2",                        
        heading:'Gestión de datos y roles',
        text:'Simplifica la gestión de usuarios, roles y formularios.',       
        description:'Simplifica la administración de usuarios y formularios mediante una plataforma intuitiva. Permite una asignación más eficiente de tareas, roles y responsabilidades, lo que agiliza los procesos laborales y garantiza una gestión más organizada y centralizada de la información.'
    },
    {
        id:26,
        bannerId:5,
        page:[ 'smart-rutines'],
        number:"3",                
        heading:'Precisión y Seguimiento',
        text:'Garantiza la precisión en las rutinas y un seguimiento en tiempo real.',       
        description:'Ofrece precisión en la ejecución de rutinas, asegurando la cumplimentación exacta de cada tarea y controlando su progreso en tiempo real. Esto permite una supervisión constante y la toma de decisiones instantáneas ante cualquier incidencia.'
    },
    {
        id:27,
        bannerId:5,
        page:[ 'smart-rutines'],                
        number:"4",                        
        heading:'Procesos industriales',
        text:'Optimiza el control de componentes y reduce errores humanos.',       
        description:'Mejora el control de los componentes industriales al minimizar la posibilidad de errores humanos, lo que conduce a una mayor eficiencia en la producción y a una reducción de tiempos inactivos debido a fallas o mal funcionamiento. Este enfoque optimizado ayuda a mantener un estándar alto y consistente en la calidad de los procesos industriales.'
    },
    {
        id:28,
        bannerId:6,
        page:['smart-rutines'],
        image:'./img/arrowup.png',
        title:'Mejora la operativdad',
        text:'Automatiza procesos y rutinas para una operatividad más eficiente.',       
    },
    {
        id:29,
        bannerId:6,
        page:[ 'smart-rutines'],        
        image:'./img/warrning.png',
        title:'Alertas inmediatas',
        text:'Genera alertas instantáneas para respuestas rápidas ante eventos críticos.',       
    },
    {
        id:30,
        bannerId:6,
        page:[ 'smart-rutines'],        
        image:'./img/fileplus.png',
        title:'Integración con sistemas actuales',
        text:'Se integra fácilmente con sistemas existentes, mejorando la coherencia de la información.',       
    },
    {
        id:31,
        bannerId:6,
        page:[ 'smart-rutines'],        
        image:'./img/chat.png',
        title:'Indicadores de interés',
        text:'Facilita la recopilación y análisis de datos para una toma de decisiones informada',       
    },
    {
        id:32,
        bannerId:7,
        page:['smart-rutines'],
        number:"1",                
        heading:'Análisis y propuesta personalizada',
        text:'Evaluación de necesidades seguida de una propuesta adaptada con detalles como licencias, soporte, costos.',
    },
    {
        id:33,
        bannerId:7,
        page:['smart-rutines'],
        number:"2",                
        heading:'Configuración y formación',
        text:'Configuración del sistema y capacitación del personal para un uso efectivo.',
    },
    {
        id:34,
        bannerId:7,
        page:['smart-rutines'],
        number:"3",                
        heading:'Consultoría y adaptación a Procesos',
        text:'Asesoramiento para integrar la asistencia remota y adaptarla a los procesos existentes.',
    },
    {
        id:35,
        bannerId:7,
        page:['smart-rutines'],
        number:"4",                
        heading:'Intalación física o virtual',
        text:'Implementación y configuración de dispositivos tecnológicos específicos',
    },
    {
        id:36,
        bannerId:7,
        page:['smart-rutines'],
        number:"5",                
        heading:'Operación regular y soporte inicial',
        text:'Uso regular del servicio con soporte técnico inicial para una implementación sin problemas.',
    },
    {
        id:37,
        bannerId:7,
        page:['smart-rutines'],
        number:"6",                
        heading:'Evaluación Continua y Mejora',
        text:'Evaluaciones constantes con actualizaciones y mejoras según las necesidades identificadas.',
    },

    {
        id:41,
        bannerId:1,
        page:['inventary-control'],
        image:'./img/Checkbox_Check.png',
        title:'Registro y configuración Inicial',
        text:'Definición de ubicaciones y categorías de los productos.',       
    },
    {
        id:42,
        bannerId:1,
        page:[ 'inventary-control'],        
        image:'./img/qr-img.png',
        title:'Etiquetas y recepción de productos',
        text:'Escaneo de productos entrantes mediante etiquetas RFID o códigos de barras.',       
    },
    {
        id:43,
        bannerId:1,
        page:[ 'inventary-control'],        
        image:'./img/List_Ordered.png',
        title:'Conteo automatizado y verificación',
        text:'Escaneo automatizado y verificación con registros en la base de datos.',       
    },
    {
        id:44,
        bannerId:1,
        page:['inventary-control'],
        image:'./img/Bell_Notification.png',
        title:'Alertas y Notificaciones',
        text:'Configuración de alertas para discrepancias y vencimientos.',       
    },
    {
        id:45,
        bannerId:1,
        page:[ 'inventary-control'],        
        image:'./img/File_Document.png',
        title:'Generación de Informes y Análisis',
        text:'Sobre movimientos de inventario, tendencias y patrones para mejorar la gestión.',       
    },
    {
        id:46,
        bannerId:1,
        page:[ 'inventary-control'],        
        image:'./img/refresh.png',
        title:'Historial y auditoría',
        text:'Historial de transacciones y auditoría para garantizar precisión e integridad en la gestión del inventario.',       
    },
    {
        id:47,
        bannerId:5,
        page:[ 'inventary-control'],
        number:"1",                
        heading:'Registro preciso',
        text:'Evita discrepancias y pérdidas de inventario causadas por errores manuales en la entrada de datos',       
        description:'Con un sistema de gestión de inventarios, se reduce la posibilidad de errores humanos al ingresar datos. Esto asegura que la información registrada sea confiable y evita pérdidas o desbalances en el inventario.'
    },
    {
        id:48,
        bannerId:5,
        page:[ 'inventary-control'],                
        number:"2",                        
        heading:'Visibilidad en tiempo real',
        text:'Proporciona visibilidad instantánea del inventario y agiliza la toma de decisiones.',       
        description:'Acceder a información actualizada del inventario de manera instantánea es clave para tomar decisiones informadas. Esta visibilidad en tiempo real permite identificar rápidamente qué productos están disponibles, su ubicación y estado, facilitando la toma de decisiones estratégicas y reaccionando ágilmente a cambios en la demanda o situaciones inesperadas.'
    },
    {
        id:49,
        bannerId:5,
        page:[ 'inventary-control'],
        number:"3",                
        heading:'Identificación y ubicación de productos',
        text:'Facilita la identificación y ubicación precisa, especialmente en almacenes grandes o complejos.',       
        description:'En almacenes grandes o complejos, la identificación y ubicación precisa de productos puede ser desafiante. Un sistema de gestión de inventarios proporciona herramientas, como etiquetas RFID o códigos de barras, que simplifican este proceso: facilita la localización exacta de productos, reduce el tiempo de búsqueda y optimiza la eficiencia en el manejo del inventario.'
    },
    {
        id:50,
        bannerId:5,
        page:[ 'inventary-control'],                
        number:"4",                        
        heading:'Planificación de reposición',
        text:'Proporciona datos precisos para una planificación efectiva de la reposición del inventario.',       
        description:'Con datos precisos y actualizados sobre el inventario, podrás planificar mejor la reposición de productos, conocer la cantidad exacta disponible, los patrones de demanda y evitar la escasez o el exceso de inventario. Esto conduce a una gestión más eficaz, reduce los costos de almacenamiento y mejora la satisfacción del cliente al mantener productos disponibles cuando se necesitan.'
    },
    {
        id:51,
        bannerId:6,
        page:['inventary-control'],
        image:'./img/chart.png',
        title:'Datos en tiempo real',
        text:'Recopila automáticamente información, sigue el progreso en la línea de producción y en la cadena de suministro.',       
    },
    {
        id:52,
        bannerId:6,
        page:[ 'inventary-control'],        
        image:'./img/Checkbox_Check.png',
        title:'Mejor eficiencia',
        text:'Agiliza las operaciones, reduce el tiempo dedicado al control de stock, previene pérdidas y robos.',       
    },
    {
        id:53,
        bannerId:6,
        page:[ 'inventary-control'],        
        image:'./img/lock.png',
        title:'Desiciones certeras',
        text:'Basadas en evidencia para optimizar recursos y responder ágilmente a cambios en la demanda.',       
    },
    {
        id:54,
        bannerId:6,
        page:[ 'inventary-control'],        
        image:'./img/chat.png',
        title:'Experiencia del cliente',
        text:'Asegura mayor disponibilidad de productos, mejorando la experiencia del cliente.',       
    },
    {
        id:55,
        bannerId:7,
        page:['inventary-control'],
        number:"1",                
        heading:'Implementación inicial',
        text:'Adaptamos el sistema según las necesidades del cliente.',
    },
    {
        id:56,
        bannerId:7,
        page:['inventary-control'],
        number:"2",                
        heading:'Configuración de hardware',
        text:'Suministramos y configuramos dispositivos clave según los requerimientos.',
    },
    {
        id:57,
        bannerId:7,
        page:['inventary-control'],
        number:"3",                
        heading:'Integración empresarial',
        text:'Asesoramiento para integrar la asistencia remota y adaptarla a los procesos existentes.',
    },
    {
        id:58,
        bannerId:7,
        page:['inventary-control'],
        number:"4",                
        heading:'Capacitación integral',
        text:'Ofrecemos una formación detallada para un uso efectivo del sistema.',
    },
    {
        id:59,
        bannerId:7,
        page:['inventary-control'],
        number:"5",                
        heading:'Desarrollo de software personalizado',
        text:'Creamos módulos específicos según los requisitos del cliente para la gestión eficiente del inventario.',
    },
    {
        id:60,
        bannerId:7,
        page:['inventary-control'],
        number:"6",                
        heading:'Soporte continuo',
        text:'Evaluaciones constantes con actualizaciones y mejoras según las necesidades identificadas.',
    }
]
