import StripeInterface from "../interface/stripeInterface";

export const STRIPE: StripeInterface[] = [
    {
        id:1,
        bannerId: 2,
        page: ['home'], 
        image:'./img/Remote-01.jpg',
        title:'Remote Assistense',
        text:'Expertos ven a través de los operarios gracias a un lente de realidad mixta. Una tecnología para la resolución clara y precisa de problemas técnicos en tiempo real.',
        buttonText:'Más información',
        buttonUrl:'/remote-assistant',
        buttonPathIcon:'M647-440H160v-80h487L423-744l57-56 320 320-320 320-57-56 224-224Z',
        imageRight:true,
    },
    {
        id:2,
        bannerId: 2,
        page: ['home'],
        image:'./img/Smart-001.jpg',
        title:'Smart routines',
        text:'Los operarios pueden realizar chequeos de forma eficiente, segura y con las manos libres, gracias a la potencia innovadora de las gafas de realidad mixta.',
        buttonText:'Más información',
        buttonUrl:'/smart-rutines',
        buttonPathIcon:'M647-440H160v-80h487L423-744l57-56 320 320-320 320-57-56 224-224Z',
        imageRight:false,
    },
    {
        id:3,
        bannerId: 2,
        page: ['home'], 
        image:'./img/img-computing.png',
        title:'Image Computing',
        text:'Imágenes convertidas en conocimiento valioso: detección de defectos, control de inventarios y alertas de seguridad. Una solución inteligente que optimiza tus operaciones y reduce costos.',
        buttonText:'Más información',
        buttonUrl:'/image-computing',
        buttonPathIcon:'M647-440H160v-80h487L423-744l57-56 320 320-320 320-57-56 224-224Z',
        imageRight:true,
    },
    {
        id:4,
        bannerId: 2,
        page: ['home'],
        image:'./img/invetary-control.png',
        title:'Control de Inventario',
        text:'Obtené un mayor control, seguimiento y administración del stock con tecnologías avanzadas que garatizan la efeciencia y agilizan la productividad.',
        buttonText:'Más información',
        buttonUrl:'/inventary-control',
        buttonPathIcon:'M647-440H160v-80h487L423-744l57-56 320 320-320 320-57-56 224-224Z',
        imageRight:false,
    },
    {
        id:5,
        bannerId: 2,
        page: ['remote-assistant'],
        image:'./img/ra-img01.png',
        title:'Manos Libres',
        text:'Esta tecnología permite que los operarios trabajen con sus manos completamente libres mientras reciben las instrucciones.',
        imageRight:true,
    },
    {
        id:6,
        bannerId: 2,
        page: ['remote-assistant'],
        image:'./img/manos-libres.jpg',
        title:'Guías visuales',
        text:'Posee guías visuales en tiempo real, para una orientación clara y precisa. Es intuitiva y fácil de usar, pensada para optimizar la productividad y llevar a tu industria a otro nivel de eficiencia.',
        imageRight:false,
    },
    {
        id:7,
        bannerId: 2,
        page: ['smart-rutines'],
        image:'./img/ra-img01.png',
        title:'Manos Libres',
        text:'Permite a los operararios ejecutar las rutinas de seguridad con las manos completamente libres, obteniendo mayor movilidad y máxima precisión.',
        imageRight:true,
    },
    {
        id:8,
        bannerId: 2,
        page: ['smart-rutines'],
        image:'./img/agus-2.png',
        title:'Gafas de realidad aumentada',
        text:'Posee guías visuales en tiempo real para una orientación clara y precisa. Es intuitiva y fácil de usar.',
        imageRight:false,
    },
    {
        id:9,
        bannerId: 2,
        page: ['inventary-control'],
        image:'./img/eficiencia.jpg',
        title:'Eficiencia operativa',
        text:'Agiliza la búsqueda de inventario, reduce errores y maximiza la eficiencia en la gestión y el control de los productos.',
        imageRight:true,
    },
    {
        id:10,
        bannerId: 2,
        page: ['inventary-control'],
        image:'./img/visibilidad-2.jpg',
        title:'Visibilidad en tiempo real',
        text:'Proporciona información actualizada de productos disponibles y favorece la toma de decisiones acertadas.',
        imageRight:false,
    }
]
